name: Java CI

on:
  push:
    branches:
      - main
    paths:
      - 'CA5-MutationCoverage/Fesadyab/**'
  pull_request:
    branches:
      - main
    paths:
      - 'CA5-MutationCoverage/Fesadyab/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.2'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: mvn -B clean install -f CA5-MutationCoverage/Fesadyab/pom.xml

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: CA5-MutationCoverage/Fesadyab/target/surefire-reports/
