name: Java CI

on:
  push:
    branches:
      - main
    paths:
      - 'CA5-MutationCoverage/Fesadyab/src/**'
      - 'CA5-MutationCoverage/Fesadyab/pom.xml'
  pull_request:
    branches:
      - main
    paths:
      - 'CA5-MutationCoverage/Fesadyab/src/**'
      - 'CA5-MutationCoverage/Fesadyab/pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -f CA5-MutationCoverage/Fesadyab/pom.xml

      - name: Run tests
        run: mvn test -f CA5-MutationCoverage/Fesadyab/pom.xml
